-- creates a function
DROP FUNCTION IF EXISTS SafeDiv;
DELIMITER $$

CREATE FUNCTION SafeDiv(a INT, b INT)
RETURNS DECIMAL(20,6)
DETERMINISTIC
BEGIN
    IF b = 0 THEN
        RETURN 0;
    END IF;

    RETURN a / b;
END$$

DELIMITER ;